# ===============================
# MySQL Datasource
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/web_app
spring.datasource.username=root
spring.datasource.password=@adi1947
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.security.user.name = aditya
spring.security.user.password = password

jwt.access.secret=kl3fULWQOqpIJd48zlFuxiICR7WUv4iFS8wfNeCKg/M8CXE89Lr53fwaaKUVOydcNYM2FZycybT5789NxEkbUQ==
jwt.refresh.secret=ArX545u1ltBTZVhVRqGzlbp+gRQJVbYfvRRlQttWlNCB91yxfwyO/2GnU66528CCoB0B0jj6yzCtL9NeVgg3+g==

jwt.access.expiration-ms=900000
jwt.refresh.expiration-ms=604800000
#acess = 15min
#refresh = 7 Days

# Mail (SMTP) Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=debnathaditya2005@gmail.com
spring.mail.password=rvzwidbqypquliuf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# Async Executor Configuration
# ===============================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=async-



spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile



spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email
